[package]
name = "rdmx"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.72.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clap_derive = "4.5"
libc = "0.2.174"
nix = { version = "0.30.1", features = ["signal", "event", "time"] }
socket2 = "0.5.10"

